---
- name: Add MongoDB repository
  ansible.builtin.copy:
    content: |
      [mongodb-org-{{ mongodb_version }}]
      name=MongoDB Repository
      baseurl={{ mongodb_rpm_repo_url }}
      gpgcheck=1
      enabled=1
      gpgkey=https://pgp.mongodb.com/server-{{ mongodb_version }}.asc
    dest: /etc/yum.repos.d/mongodb-org-{{ mongodb_version }}.repo
    mode: "0644"

- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: present
    update_cache: true
  notify:
    - Start mongodb

- name: Install pip3
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Ensure pymongo is installed and up-to-date
  ansible.builtin.pip:
    name: pymongo
    state: present
