---
namespace: pscloud
name: vps
version: 1.1.0
readme: README.md
authors:
  - Ivan Sukhanov <ivan.sukhanov@ps.kz>

description: VPS setup collection

license:
  - GPL-2.0-or-later

repository: https://github.com/supervillain3000/VPS-Setup-Playbooks.git
