---
- name: Restart php-fpm centos
  ansible.builtin.service:
    name: php{{ _phpmyadmin_php_version }}-php-fpm
    state: restarted

- name: Restart php-fpm debian
  ansible.builtin.service:
    name: php{{ _phpmyadmin_php_version }}-fpm
    state: restarted

- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
