---
- name: Set up wp-config
  ansible.builtin.template:
    src: "wp-config.php.j2"
    dest: "/var/www/{{ vhost }}/wp-config.php"
    group: www-data
    owner: www-data
    mode: "0644"

- name: Set permissions for directories
  ansible.builtin.file:
    dest: /var/www/{{ vhost }}/
    owner: www-data
    group: www-data
    recurse: true
