---
- name: Install angular-cli
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: "present"
  environment:
    NPM_CONFIG_PREFIX: "{{ nodejs_npm_config_prefix }}"
    NODE_PATH: "{{ nodejs_npm_config_prefix }}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "false"
  with_items: "{{ nodejs_npm_global_packages }}"

- name: Clone the Git repo if not already present
  ansible.builtin.git:
    repo: https://github.com/scotch-io/node-todo.git
    version: master
    dest: /var/www/{{ nodejs_domain }}

- name: Update packages based on package.json to their latest version
  community.general.npm:
    path: /var/www/{{ nodejs_domain }}
    state: latest

- name: Check if mongodb cred file exists
  ansible.builtin.stat:
    path: /root/03-mongo_password
  register: mongo_password_check

- name: Load the database access data
  ansible.builtin.slurp:
    src: /path/to/your/file.txt
  register: db_access_data

- name: Decode and parse the password
  ansible.builtin.set_fact:
    _nodejs_mongodb_password: "{{ db_access_data['content'] | b64decode | regex_search('Password:\\s*(\\S+)') }}"

- name: Update MongoDB user and password in localUrl
  ansible.builtin.lineinfile:
    path: /var/www/{{ nodejs_domain }}/config/database.js
    regexp: '^\\s*localUrl:'
    line: "    localUrl: 'mongodb://{{ nodejs_domain_short }}:{{ _nodejs_mongodb_password }}@localhost:27017'"
    backrefs: true
  when: mongo_password_check.stat.exists

- name: Start application with "pm2"
  ansible.builtin.shell: >
    pm2 start /var/www/{{ nodejs_domain }}/server.js --name angular-test-app
  changed_when: false

- name: Add nginx vhost config
  ansible.builtin.template:
    src: "vhost.conf.j2"
    dest: "/etc/nginx/vhosts/{{ nodejs_domain }}.conf"
    mode: "0644"
  notify: Restart nginx
