---
- name: Choose Docker repo distro (ubuntu/debian)
  ansible.builtin.set_fact:
    docker_repo_distro: "{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }}"
  changed_when: false

- name: Ensure keyrings dir
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ docker_repo_distro }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true

- name: Add Docker apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ docker_repo_distro }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_pkgs }}"
    state: present
    update_cache: yes
  become: true

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: true
