---
- name: Install python modules
  ansible.builtin.apt:
    name:
      - python3-venv
      - uwsgi
      - uwsgi-plugin-python3
      - gcc
      - python3-setuptools
    state: present

- name: Add uwcgi config
  ansible.builtin.template:
    src: "uwsgi.ini.j2"
    dest: "/etc/uwsgi/apps-available/{{ vhost }}.ini"
    mode: "0644"

- name: Create uwsgi ini symbolic link
  ansible.builtin.file:
    src: "/etc/uwsgi/apps-available/{{ vhost }}.ini"
    dest: "/etc/uwsgi/apps-enabled/{{ vhost }}.ini"
    state: link

- name: Add nginx vhost config
  ansible.builtin.template:
    src: "vhost.conf.j2"
    dest: "/etc/nginx/vhosts/{{ vhost }}.conf"
    mode: "0644"
  notify: Restart nginx
