---
- name: Install python modules
  ansible.builtin.dnf:
    name:
      - gcc
      - python3-devel
      - uwsgi
      - uwsgi-plugin-python3
      - python3-setuptools
    state: present

- name: Add uwsgi config
  ansible.builtin.template:
    src: "uwsgi.ini.j2"
    dest: "/etc/uwsgi.d/{{ django_domain }}.ini"
    mode: "0644"
    owner: django
    group: nginx

- name: Restart and enable uwsgi
  ansible.builtin.systemd:
    name: uwsgi
    state: restarted
    enabled: true

- name: Add nginx django_domain config
  ansible.builtin.template:
    src: "django_domain.conf.j2"
    dest: "/etc/nginx/conf.d/{{ django_domain }}.conf"
    mode: "0644"
  notify: Restart nginx
