---
mongodb_domain_name_short: "{{ short_vhost }}"
mongodb_version: "8.0"

mongodb_rpm_repo_url: https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}/mongodb-org/{{ mongodb_version }}/x86_64/
