---
- name: Allow nginx to connect to upstream (SELinux)
  ansible.builtin.command: setsebool -P httpd_can_network_connect 1
  changed_when: false
  become: true

- name: Label ACME webroot for nginx (SELinux)
  ansible.builtin.command: chcon -R -t httpd_sys_content_t /var/www/{{ vhost }}
  changed_when: false
  become: true
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"
