---
php_default_version: "8.2"
php_default_version_short: '82'

php_debian_packages:
  - php{{ php_default_version }}-common
  - php{{ php_default_version }}-cli
  - php{{ php_default_version }}-dev
  - libpcre3-dev
  - php{{ php_default_version }}-gd
  - php{{ php_default_version }}-curl
  - php{{ php_default_version }}-imap
  - php{{ php_default_version }}-opcache
  - php{{ php_default_version }}-xml
  - php{{ php_default_version }}-mbstring
  - php{{ php_default_version }}-apcu
  - php{{ php_default_version }}-sqlite3
  - php{{ php_default_version }}-dom
  - php{{ php_default_version }}-dev
  - php{{ php_default_version }}-intl
  - php{{ php_default_version }}-mysql
  - php{{ php_default_version }}-zip
  - php{{ php_default_version }}-soap
  - php{{ php_default_version }}-imagick
  - php{{ php_default_version }}-pdo
  - libapache2-mod-php{{ php_default_version }}

php_redhat_packages:
  - php{{ php_default_version_short }}-php-common
  - php{{ php_default_version_short }}-php-cli
  - php{{ php_default_version_short }}-php-devel
  - pcre-devel
  - php{{ php_default_version_short }}-php-gd
  - php{{ php_default_version_short }}-php-curl
  - php{{ php_default_version_short }}-php-imap
  - php{{ php_default_version_short }}-php-opcache
  - php{{ php_default_version_short }}-php-xml
  - php{{ php_default_version_short }}-php-mbstring
  - php{{ php_default_version_short }}-php-apcu
  - php{{ php_default_version_short }}-php-sqlite3
  - php{{ php_default_version_short }}-php-dom
  - php{{ php_default_version_short }}-php-intl
  - php{{ php_default_version_short }}-php-mysql
  - php{{ php_default_version_short }}-php-zip
  - php{{ php_default_version_short }}-php-soap
  - php{{ php_default_version_short }}-php-imagick
  - php{{ php_default_version_short }}-php-pdo

php_apt_repo_gpg_key: "https://mirror.ps.kz/sury/packages.sury.org/php/apt.gpg"

php_sury_repo: "deb https://mirror.ps.kz/sury/packages.sury.org/php {{ ansible_facts['distribution_release'] }} main"
php_redhat_remi_repo: "http://mirror.neolabs.kz/remi/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"

php_enable_php_fpm: false
