---
- name: Restart webserver
  ansible.builtin.service:
    name: "{{ __php_webserver_daemon }}"
    state: restarted
    enabled: true
  notify: Restart php-fpm

- name: Restart php-fpm
  ansible.builtin.service:
    name: "{{ __php_fpm_daemon }}"
    state: restarted
    enabled: true
  when:
    - php_enable_php_fpm
    - not ansible_check_mode
